version: '3.8'

services:
  mediasoup-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediasoup-livestream
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=${MEDIASOUP_ANNOUNCED_IP}
    networks:
      - mediasoup-network
    # Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mediasoup-network:
    driver: bridge