name: Docker Build and Push

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate self-signed SSL certificates
        run: |
          openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=localhost"

      - name: Build development Docker image
        run: docker-compose build

      - name: Start development services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Check if services are running
        run: docker-compose ps

      - name: Check service health
        run: |
          curl -k https://localhost:8443 || echo "HTTPS endpoint not responding, but this might be expected if the server is still starting"

      - name: Stop services
        run: docker-compose down

  build-production:
    runs-on: ubuntu-latest
    needs: build-and-test-dev
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mediasoup-livestream:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mediasoup-livestream:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mediasoup-livestream:buildcache,mode=max